### PR TITLE
Fixed tiny typo

### PR DESCRIPTION
**Pull request by wo0dyn**

### CODE REVIEW

**Comment by chrisanderton** [comment]
Forgo (not forgot) was the correct word - http://www.oxforddictionaries.com/definition/english/forgo

**Comment by wo0dyn** [comment]
My mistake. Sorry about that. :wink: 
_(Got to learn English someday)_

**Comment by chrisanderton** [comment]
Believe me, your english is probably better than mine, and for me it is my first language! (nice picture!)

**Pull request closed without merging**
