### PR TITLE
.empty() replacement

### PR DESCRIPTION
**Pull request by rkrupinski**
Changed '.empty()' equivalent to something that appears to be much faster.
Build script generated whole lot of stuff...

### CODE REVIEW

**Comment by zackbloom** [comment]
Just out of curiosity, do you have a link to jsperf or the like showing the performance difference?

**Comment by rkrupinski** [comment]
http://jsperf.com/innerhtml-vs-removechild/15

**Comment by zackbloom** [comment]
That's just crazy

**Comment by zackbloom** [comment]
Actually, it is crazy, that test only adds content the first time it gets ran.

**Comment by zackbloom** [comment]
It took me bizarrely long to find a real comparison: http://jsperf.com/innerhtml-vs-removechild/133

**Comment by rkrupinski** [comment]
I definitely need to get myself one of these
Brain

**Comment by wyuenho** [comment]
While `innerHTML` is known to be faster since forever, but `while(element.firstChild) element.removeChild(element.firstChild)` is far safer because setting `innerHTML` to `''` will sometimes throw `Error: Unknown runtime error` in IE8 for invalid HTML and table elements like `thead` `tbody` and `tfoot`.

**Comment by wyuenho** [comment]
> The innerHTML property is read-only on the col, colGroup, frameSet, html, head, style, table, tBody, tFoot, tHead, title, and tr objects.

http://msdn.microsoft.com/en-us/library/ms533897.aspx

Inserting `li` under `p`.
http://blog.rakeshpai.me/2007/02/ies-unknown-runtime-error-when-using.html

jQuery's 1.x branch uses the DOM method too:
https://github.com/jquery/jquery/blob/1.11.0/src/manipulation.js#L541

If you are going to advocate a more or less 1 to 1 mapping from jQuery to Vanilla JS, DOM API should be the correct answer.

**Comment by rkrupinski** [comment]
I also prefer the DOM API method due to inconsistencies (Internet Explorer) when referencing children of nodes detached with .innerHTML=''.

http://jsfiddle.net/7bms2/
vs.
http://jsfiddle.net/YkG2B/

**Comment by wyuenho** [comment]
@zackbloom still not changing `innerHTML = ''` to the while loop?

**Comment by zackbloom** [comment]
Just fixed, under the assumption that this is only an issue on IE8.  If that's not the case, please comment.

**Pull request merged**
