### PR TITLE
classList only supports a single class per argument

### PR DESCRIPTION
**Pull request by zachleat**

### CODE REVIEW

**Comment by sindresorhus** [comment]
nope, https://developer.mozilla.org/en-US/docs/Web/API/Element.classList#Example, though Firefox may not.

**Comment by zachleat** [comment]
Sorry, incorrect title—poor wording there. The PR/code still makes sense though.

**Comment by zackbloom** [comment]
I think add class is not the same as add classes.  I do appreciate the potential for confusion though, when we add the ability to include comments with the sections, we'll make mention of it.

Another option, of course, is to add a section called addClasses that does properly loop.  If you do make a PR for that, please do it in the comparisons/ tree.

**Comment by zachleat** [comment]
Hm? You do realize that jQuery’s addClass supports multiple space delimited classes in a single string, right? jQuery doesn’t use an addClasses method.

**Comment by zackbloom** [comment]
The question then is, is the title of a section describing what the section does, or what jQuery calls it.

**Comment by zachleat** [comment]
Fair point. Might be worth clarifying.

**Comment by zackbloom** [comment]
I think adding a new section for Add Classes is the best way to go, that way people who only need once class don't think the native solution is unnecessarily complex.

**Comment by zachleat** [comment]
Careful, you almost sound like you’re recommending the jQuery API :)

**Comment by zackbloom** [comment]
I'm recommending a layer that might abstract class adding, I'm not sure this could be taken as an endorsement for `$.type` :).

**Pull request closed without merging**
