### PR TITLE
Add target IE version to URL query parameter

### LINKED ISSUE #180: Add "IE Version" toggle to query string
I think changing the IE Version should change the query string so we can bookmark it.

image

Also, it would be nice to add IE 11 (if there are any differences)

### PR DESCRIPTION
**Pull request by jarikmarwede**
This PR uses [URLSearchParams](https://caniuse.com/urlsearchparams). I hope it's no problem if this does not work in ie11.

I wanted to put the new functions into their own file, but trying to import them crashed the dev server. If someone knows how to set up importing in CoffeeScript, please let me know. But maybe this can also wait until someone does #162 

Closes: #180

### CODE REVIEW

**Review by nickserv — APPROVED** [review]

**Review by Abbondanzo — COMMENTED** [review]
@nickmccurdy has a branch in #249 that I hope to merge in soon. If you want to branch off of that to make these changes, I'll review it then

**Comment by jarikmarwede** [comment]
Depending on how the final decision is in #222 this might need to be changed again so until then it would probably be good to wait

**Comment by nickserv** [comment]
> @nickmccurdy has a branch in #249 that I hope to merge in soon. If you want to branch off of that to make these changes, I'll review it then

I don't think we have a bundler yet, but I was thinking of setting one up.

**Comment by nickserv** [comment]
#249 has been merged, and while it doesn't have a bundler, you could add scripts to the generated `index.html`.

Also for IE compatibility, you should be able to polyfill URLSearchParams similarly.

**Comment by jarikmarwede** [comment]
> #249 has been merged, and while it doesn't have a bundler, you could add scripts to the generated `index.html`.
> 
> Also for IE compatibility, you should be able to polyfill URLSearchParams similarly.

Yup, I'll adapt it soon.
Is IE compatibility needed @Abbondanzo? This looks like the site supported IE10 https://github.com/HubSpot/youmightnotneedjquery/blob/dev/src/jade/index.jade#L32

**Comment by jarikmarwede** [comment]
The branch is now updated and if IE support is not needed it is ready to be merged

**Comment by Abbondanzo** [comment]
> > #249 has been merged, and while it doesn't have a bundler, you could add scripts to the generated `index.html`.
> > Also for IE compatibility, you should be able to polyfill URLSearchParams similarly.
> 
> Yup, I'll adapt it soon. Is IE compatibility needed @Abbondanzo? This looks like the site supported IE10 https://github.com/HubSpot/youmightnotneedjquery/blob/dev/src/jade/index.jade#L32

Ideally we could add a polyfill for this. It would be a tad bit ironic if we added selectors for different versions of IE but the site's main scripts crashed in those browsers. There are some decent polyfills like [this one](https://www.npmjs.com/package/url-search-params-polyfill) which add support for `URLSearchParams`. #265 has noted a few more errors that will need some TLC in IE11

**Comment by nickserv** [comment]
Alternatively, we could pre/server render the app so it would gracefully degrade to serving HTML files on IE see #266). You would lose your analytics unless it supports running on the edge/server though.

**Comment by jarikmarwede** [comment]
> Alternatively, we could pre/server render the app so it would gracefully degrade to serving HTML files on IE see #266). You would lose your analytics unless it supports running on the edge/server though.

I don't think SSR would work because AFIK the site is only deployed to Github Pages. 
Pre-rendering could work, but some things, like the star count or which code examples to show based on the query string and slider, have to be loaded dynamically anyways.

**Comment by jarikmarwede** [comment]
I tried to add a polyfill from [Polyfill.io](https://polyfill.io/v3/url-builder/) but I can not really test if it works because of #265.
I think that I will have to wait again until that one is fixed.

**Review by Abbondanzo — APPROVED** [review]

**Comment by qgustavor** [comment]
Was there a regression of this feature after https://github.com/HubSpot/youmightnotneedjquery/pull/275? It's not working here.

**Comment by Abbondanzo** [comment]
> Was there a regression of this feature after #275? It's not working here.

We've removed it but can't hurt to add it back

**Pull request merged**
