### PR TITLE
As suggested in Issue #41

### PR DESCRIPTION
**Pull request by vc0d35**

### CODE REVIEW

**Comment by vc0d35** [comment]
Didn't really know if it should be categorized as utils...

**Comment by zackbloom** [comment]
Thanks @vicnicius

**Comment by 7cc** [comment]
ah...this is closed, but
you can't use `el.currentStyle` instead of `getComputedStyle`

``` html
<div style="margin: 1em">
```

``` js
el.currentStyle.marginTop // 1em
getComputedStyle.marginTop // 16px
```

as suggested in
https://github.com/HubSpot/youmightnotneedjquery/blob/gh-pages/br/index.html#L677

**Comment by vc0d35** [comment]
Thanks for pointing that out, @7cc . Will fix it asap. Actually I had this wrong assumption of `currentStyle` returning only explicit style values.

**Pull request merged**
