### PR TITLE
Change "what jQuery does for you" link into a github repo

### PR DESCRIPTION
**Pull request by gregsabo**
@rwaldron @jdalton @paulirish

May I suggest that we host your list of bugs on Github? Using Google Docs makes it more difficult for others to add to and improve it. I've created a new repo called "whatjquerydoesforyou" to demonstrate what I mean,  and I've ported the content from the original note into Markdown format:

https://github.com/gregsabo/whatjquerydoesforyou/blob/master/README.md

If you like, feel free to move the README into a repo of your own since it's all your content.

### CODE REVIEW

**Comment by rwaldron** [comment]
@gregsabo, that list is generated from source annotations, I don't think we _want_ others to add to it and the only improvements I care about are fixes to the browsers responsible for creating the issue.

**Comment by gregsabo** [comment]
Okie dokie. But isn't it inconsistent to use the open-source nature of YMNNJQ to change its message while also publishing your own page in a closed-source manner? Just food for thought.

**Comment by rwaldron** [comment]
@gregsabo it's not "closed source"—those are literally just links to lines of built source code posted publicly in a github gist. Your claim is made further absurd in that all of those _generated_ line numbers are _generated_ from open source code. I actually don't want _any_ person to come along and start adding, deleting or modifying lines from the list; all that will do is create confusion—the list is ONLY issues that jQuery and Sizzle address, so what use is it for other people to add issues that aren't relevant to that description? If people start deleting items, how will @bz_moz and I be able to track progress? The list is openly available, unobfuscated, free for you to do whatever you'd like, but the data is readonly to maintain its integrity—that doesn't make it closed-source.

**Comment by gregsabo** [comment]
@rwaldron Ah, I didn't realize that the list of issues was generated by a _script_. I thought it would be cool to add more links to other interesting parts of the jQuery codebase, but I was under the impression that the list was generated "by hand". Sorry for the confusion.

**Pull request closed without merging**
