### PR TITLE
Make version sliders labels clickable

### LINKED ISSUE #247: Range labels should be clickable for accessibility

### PR DESCRIPTION
**Pull request by jarikmarwede**
Closes: #247

### CODE REVIEW

**Comment by nickserv** [comment]
I was thinking it would be good to also have screenreader support, so there would be an established relationship between the labels, and the ability to control the labels with the keyboard. You should be able to use `label` tags or the `aria-labelledby` attribute for that.

**Comment by jarikmarwede** [comment]
I am not sure how that would work. The "What's the oldest version of IE you need to support?" text is set as the label for the slider and if you focus the slider you can manipulate it with the arrow keys.
Once the slider doesn't contain the "N/A" option anymore the slider should be accessible to screenreaders again. Or am I missing something?

**Comment by mscuthbert** [comment]
For screenreaders, I think that the slider should be not shown and the clickable labels are the preferred interface, since N/A is better than "12"

**Comment by nickserv** [comment]
Maybe it would be easier to use a native range or select for IE along with #272

**Comment by jarikmarwede** [comment]
> Maybe it would be easier to use a native range or select for IE along with #272

That sounds like a great idea

**Pull request closed without merging**
