### PR TITLE
made offset work with elements out of the normal page flow

### PR DESCRIPTION
**Pull request by NickBeeuwsaert**

### CODE REVIEW

**Comment by 7cc** [comment]
It's not correct.

## what jQuery does

``` js
// jQuery
$(sel).offset().top
// pure JS
el.getBoundingClientRect().top + pageYOffset - document.documentElement.clientTop
```

and it should be, in fact

``` js
el.getBoundingClientRect().top + pageYOffset
```

In Firefox, `document.documentElement.clientTop` returns always 0

## Never use el.offsetTop / el.offsetLeft
1. visit: http://jsbin.com/aWIkIVIN/2/edit?css,js,output
2. open console, see the diffrence

Many people misunderstand `offsetTop` somehow.

**Comment by NickBeeuwsaert** [comment]
using offsetLeft/offsetTop is just how I learned in on quirksmode. 
I see the point of using `elem.getBoundingClientRect()` however, your code is only consistent in FF.
I'll update the code to read

```
var offset = function(el){
box = el.getBoundingClientRect();
docElem = document.documentElement;
return {
        top: box.top  + ( window.pageYOffset || docElem.scrollTop )  - ( docElem.clientTop  || 0 ),
        left: box.left + ( window.pageXOffset || docElem.scrollLeft ) - ( docElem.clientLeft || 0 )
    };
};
```

which is pretty much just ripped out of jQuery, anyway

**Comment by 7cc** [comment]
I’ve just undersood the reason `- docElem.clientTop` now.
It returns 2 in IE7.
`document.documentElement.clientTop // 2`
Maybe someone should open a issue for jQuery.

Note: `- docElem.clientTop` shold not be used in all browsers, not only in FF.
Try this code in the link above

``` js
var rect = td2.getBoundingClientRect()
scrollBy(rect.left, rect.top)
```

You can scroll to the element position in all browsers.

**Comment by zackbloom** [comment]
@NickBeeuwsaert Thanks.  Three things:
- Fix the tabbing of the function please
- Create an ie9.js that removes the scrollTop and Left fallbacks, as the page offsets are available everywhere but ie8.
- Is there any way for us to confirm that the clientTop and Left corrections are required for IE8+?

**Comment by NickBeeuwsaert** [comment]
I tested in IE8-11, and the corrections don't seem to need to be there, and according to an (old) quirksmode article, clientTop exists in all browsers [here](http://www.quirksmode.org/dom/w3c_cssom.html)

**Comment by Abbondanzo** [comment]
Closing in favor of #251

**Pull request closed without merging**
