### PR TITLE
Adds link to annotated list of jQuery's browser bug workarounds

### PR DESCRIPTION
**Pull request by rwaldron**

### CODE REVIEW

**Comment by zackbloom** [comment]
@rwaldron @jdalton @paulirish

The document in question for the lazy: https://docs.google.com/document/d/1LPaPA30bLUB_publLIMF0RlhdnPx_ePXm7oW02iiT6o

Wow, thanks for writing that up.

As I see it, there are two questions here:

#### Are modern browsers conformant enough to not have to use a compatibility layer?

The answer is, it depends.  For somethings, like basic manipulation with `document.querySelector`, probably.  For others, probably not.  We are, however looking towards a future where it is a very real possibility, and I hope this site can be a resource when android 2.3 and IE9 die.

#### Should that compatibility layer be jQuery?

My personal answer to that is no.  I think that jQuery served a very important purpose in the history of the web, but I don't think combining promises, events, DOM manipulation, arbitrary utilities and AJAX into a single thing is good.  Now that we're just starting to get real dependency management on the client, I believe that the future is in small, single purpose libraries.

That's why our move looking forward is to link each example to one or more such library (when necessary), which can provide compatibility, without bringing along the kitchen sink.  If it makes sense we will include links to the jQuery custom build resources to allow people to use the experience of the jQuery developers in filling in some of these needs.

A big part of my point comes down to what you said "jQuery core is very careful not to bloat their codebase and does not add features or fixes without serious consideration and peer review."  This is not how I want us to build things.  I want people to be able to create RSVP, and Q, and a dozen other promise libraries and let people depend on what they think is best.  I don't think there should be a grand cabal deciding how promises work.  I just don't think it's possible to end up with the best ecosystem that way.  Helping libraries eliminate their dependency on jQuery is a big part of making that world a reality.

Linking to your document from a resource which advocates the (somewhat) opposing position is a bit of a tricky question, but we have too much respect for you guys to do anything else, merging.

**Comment by jdalton** [comment]
@zackbloom 

Wow, thanks for merging the PR.

> and I hope this site can be a resource when android 2.3 and IE9 die

Could you express that in the site's message? Currently it just has the snarky line:

> Some developers believe that jQuery is protecting us from a great demon of browser incompatibility

**Comment by jdalton** [comment]
@zackbloom

> I want people to be able to create RSVP, and Q, and a dozen other promise libraries and let people depend on what they think is best.

Not sure jQuery is preventing devs from using either RSVP or Q. What I've seen however is most DOM microlibs are hard pressed to hold up in terms of quality/support when compared to jQuery.

If you want small more focused code then jQuery's custom builds is where it's at.
jQuery is now [defined as AMD modules](http://blog.jquery.com/2014/01/24/jquery-1-11-and-2-1-released/). You and Adam could even pitch in and help refine it further.

**Comment by zackbloom** [comment]
What's your argument here, that it isn't possible to build a quality DOM microlibrary, so we better use the one thing we've got?  It seems like it's becoming a bit of an argument for jQuery simply because _it's jQuery_.

I get that jQuery is well maintained, that's not the same as it fitting within the goals that I put forward in my comment.  If npm has taught us anything, it's that people will build modules, and the good ones will get maintained.

**Comment by jdalton** [comment]
> What's your argument here, that it isn't possible to build a quality DOM microlibrary, so we better use the one thing we've got? It seems like it's becoming a bit of an argument for jQuery simply because it's jQuery.

I'm saying most devs lack the experience to create a quality DOM lib that has the issue coverage and support of jQuery. jQuery has the advantage of having a rich history, experienced devs, and lots of other devs using it.

> If npm has taught us anything, it's that people will build modules, and the good ones will get maintained.

~~I'm not so sure about that. For example, Underscore is the number one depended on npm package and its unit tests don't even run in Node.~~ Also, take my own Benchmark.js. It's great, the best at what it does, but I haven't gotten around to bumping its npm version in over a year :O

**Comment by zackbloom** [comment]
> I'm saying most devs lack the experience to create a quality DOM lib that has the issue coverage and support of jQuery.

I'm sure that's true, but it comes back to the same two issues, one is, can a developer create an element or make something hidden without jQuery.  The second is, can _someone_ build a DOM manipulation library which has the potential to be better than jQuery and maintain it.  As long as those things are true, I'm going to continue advocating for both parts.

I agree that we need to be more explicit about what the limitations of the various options are, but that's not the same as saying that everybody needs to drive a Mack truck to the supermarket.  [Not because I care how big jQuery is, but because I don't think it's necessary to walk around with bugfixes for things you're not doing].

> Underscore is the number #1 depended on npm package and its unit tests don't even run in Node.

I'm sure it's tests running in node would be good, but them not working is not the same as it being a broken or unmaintained project.  It certainly doesn't mean the solution is to build one giant NodeUtils library which includes a whole bunch of different tools, just to facilitate maintenance.  Doing that would, among other things, have made it harder for you to come along and provide a replacement in lodash.

**Comment by jdalton** [comment]
> can a developer create an element or make something hidden without jQuery

Yes, but they may not know that button elements created can't have their type set in IE < 9 unless you do it like `document.createElement('<button type="reset">')`, and that it will break in IE9 and up if you try that, or that hidden elements or children of hidden elements may have issues detecting their dimensions, and on and on.

> I agree that we need to be more explicit about what the limitations of the various options are, but that's not the same as saying that everybody needs to drive a Mack truck to the supermarket.

Not everyone is capable of working under the hood (oh noes car related jabber).

**Comment by zackbloom** [comment]
When your distributor cap is mistimed, you don't adjust the carburator.... just kidding.

I don't have a problem with using libraries, I think that libraries that encapsulate complex functionality are great, I just don't like the idea of only having one monolithic one.  And I believe that we are capable of building really great microlibraries that are maintained by passionate people who care about these issues.

**Comment by jdalton** [comment]
> Again though, I don't have a problem with using libraries, just the idea of one monolithic one.

I've noticed that trying to cobble together a collection of microlibs with consistent support & compatibility is pretty challenging. What's great about a monolithic lib that is customizable or even modularizable (made up that word) is that there's a shared style/compatibility/support across all of its parts.

For example you could get an `extend` or `map` package from npm but you'll be hard pressed to find a collection of packages with consistent support. I manage to do that with Lo-Dash, a monolithic lib, that's customizable and modularizable. So now [there are packages](https://npmjs.org/browse/keyword/lodash-modularized) with uniform style/compat/support/test-coverage.

I think the same thing can be done with jQuery and it's moving in that direction.

**Comment by zackbloom** [comment]
It's a bit of a difference in scope.  You are combining `map` and `extend` into one library, jQuery is combining AJAX and DOM manipulation.

I don't really think that we get anything from combining such disparate libraries.  I would just as soon let them be solved their own way, and not bother trying to make it jQuery.AJAX and jQuery.DOM, but I'm happy to link to those components when they are available.

**Comment by jdalton** [comment]
> It's a bit of a difference in scope.

Naw, we've got arrays methods, objects methods, string methods, and templates.
Each could [stand on their own](http://epeli.github.io/underscore.string/).

Most people don't mind though. It's easier for them to get their utilities in 1 place instead of hunting for ones that work well or share the same support as each other. I've focused on making the best utility lib possible, letting devs slice it up how they see fit is icing on the cake. jQuery is the best DOM lib you'll find atm. Letting devs slice it up is the next step.

**Comment by zackbloom** [comment]
I think the DOM manipulation chaining style leads to a coding style which doesn't have any variables, making it very difficult to read.  I also think that jQuery's AJAX API has some warts on it, and someone could do a cleaner job taking a fresh pass at it.  I also think that its promise API is not great.

My point is not that jQuery sucks, it doesn't.  My point is it would be nice if we could have real change in these areas, but I see it as difficult as long as jQuery is used mindlessly.

I appreciate that having one big library is convenient, but people seem to manage to build node apps, I don't see why the frontend would be any different.

>  I've focused on making the best utility lib possible.

I think that's great.  I think jQuery at this point is just too invested and too big to make some of the changes necessary to make it the 'best anything lib possible', particularly for everyone.

**Comment by jdalton** [comment]
> I think the DOM manipulation chaining style leads to a coding style which doesn't have any variables, making it very difficult to read. I also think that jQuery's AJAX API has some warts on it, and someone could do a cleaner job taking a fresh pass at it. I also think that its promise API is not great

So it looks like you have an issue with chaining, ajax, and promises. Why not help fix those areas instead of trying to throw the baby out with the bath water?

> I appreciate that having one big library is convenient, but people seem to manage to build node apps, I don't see why the frontend would be any different.

It's the fact that Node is V8 only, browsers introduce a lot more versions, vendors, and compat issues.

**Comment by zackbloom** [comment]
> So it looks like you have an issue with chaining, ajax, and promises. Why not help fix those areas instead of trying to throw the baby out with the bath water.

It's a little silly to think that the jQuery team are interested in revolutionary experiments in style.  Or getting rid of chaining.  And I don't really think they should be, jQuery is chaining.  I think that developers should be free to pick the way they want to interact with the DOM.

> It's the fact that Node is V8 only, browsers introduce a lot more versions, vendors, and compat issues.

I don't think the compatibility question is really relevant.  Nothing prevents a small-module developer from fixing incompatibility bugs.  As a library developer I would sooner take ownership of the issues of a small module that fixes one incompatibility than a giant library that fixes all of them.

**Comment by jdalton** [comment]
> It's a little silly to think that the jQuery team are interested in revolutionary experiments in style. Or getting rid of chaining. And I don't really think they should be, jQuery is chaining. I think that developers should be free to pick the way they want to interact with the DOM.

You could contribute in different ways. For example you could write a post explaining how to create a custom build of jQuery w/o promises and hook it into your favorite promises lib. Or you could write an adapter that makes its `$.fn` methods adapted as generic methods. It's totally possible to write adapters over the solid DOM processing guts of jQuery.

> I don't think the compatibility question is really relevant.

Compat is totally relevant. It means more testing, VMs, time to spend getting things to work. The cost is higher. The DOM is incredible hard to work with.

**Comment by zackbloom** [comment]
> You could contribute in different ways. For example you could write a post explaining how to create a custom build of jQuery w/o promises and hook it into your favorite promises lib. Or you could write an adapter that makes its $.fn methods adapted as generic methods. It's totally possible to write adapters over the solid DOM processing guts of jQuery.

Ignoring my personal issue with the concept of hacks piling on top of hacks, this wouldn't really help, as since every library depends on jQuery, you can't make a custom build with a different promise lib and expect anything depending on jq to work.  If only there was some way of having the world's libraries not depend on jQuery /s.

> Compat is totally relevant. It means more testing, VMs, time to spend getting things to work. The cost is higher. The DOM is incredible hard to deal with.

I think working on ways of lowering the overhead of doing browser testing is a great idea.  TravisCI and the VM services that link up with it have made some progress, maybe if it was a bit easier to get up and running.  That I _will_ write a blog post on.

**Comment by jdalton** [comment]
> If only there was some way of having the world's libraries not depend on jQuery /s.

It's hard. I think you'd have to create a lib or a collection of modules that are customizable/configurable with the same/higher level of compatibility/support. It may be easier to move jQuery in that direction through finer-grained-builds/smaller modules.

> I think working on ways of lowering the overhead of doing browser testing is a great idea. TravisCI and the VM services that link up with it have made some progress, maybe if it was a bit easier to get up and running. That I _will_ write a blog post on.

I wouldn't mind helping with that.

**Comment by zackbloom** [comment]
> It's hard. I think you'd have to create a lib or a collection of modules that are customizable/configurable and with the same/higher level of compatibility/support. It may be easier to move jQuery in that direction through finer grained builds.

Maybe.  Or maybe we can get away with DOM libs, promise libs and ajax libs that don't need to share much.  If everyone standardizes around ECMA6 polyfills we'll at least have a standard way of interacting with promises.

I really don't want it to be a single library or collection of modules maintained by a single team, I don't think that's conducive to innovation, but fortunately for the world, I don't actually control what anybody does, so we'll have to see what happens.

**Comment by jdalton** [comment]
> Maybe. Or maybe we can get away with DOM libs, promise libs and ajax libs that don't need to share much. 

I don't think it's unreasonable at some point for jQuery to split them out. Though you could do that now with custom builds. I feel like this thread is kind of going in circles though :P

**Comment by ghost** [comment]
I run one of those automated cross-browser testing services. Just add a "testling" field in your package.json poiting to your test files and what browsers you want to run testling in ([example](https://github.com/substack/insert-css/blob/master/package.json#L15-L25)), add a github webhook for http://git.testling.com, then get one of these badges at https://ci.testling.com/$USER/$REPO.png:
[dnode](http://ci.testling.com/substack/dnode)

Tiny modules ftw! Tiny modules can have all the infrastructure that big projects have.

**Comment by jdalton** [comment]
> I run one of those automated cross-browser testing services.

Yap, though I prefer [sauce labs](https://saucelabs.com/u/lodash), automated browser testing is a big win.

**Comment by adamschwartz** [comment]
> I don't think it's unreasonable at some point for jQuery to split them out.

This is really the key to what we're after. We should certainly take all of the incredible learning that has come from solving compatibility issues. But by packaging jQuery modules separately we additionally get the value that each one must stand on its own and compete with any other library which claims to accomplish the same task. This will lead to a healthier ecosystem of single-purpose libraries which will lead to less complicated dependency incompatibility issues.

**Comment by jdalton** [comment]
> This is really the key to what we're after. We should certainly take all of the incredible learning that has come from solving compatibility issues.

Yes!

> But by packaging jQuery modules separately we additionally get the value that each one must stand on its own and compete with any other library which claims to accomplish the same task.

Yes!

> This will lead to a healthier ecosystem of single-purpose libraries which will lead to less complicated dependency incompatibility issues.

Yes!

The thread took an interesting turn... but

**Comment by dmethvin** [comment]
The jQuery team doesn't object to splitting things out either. It's a question of cost in time/space/performance/compatibility versus proportion of the community that benefits.

The number of web developers who use a build system and dependency management is small compared to the total universe of web developers who just want to include the one file and be done with it. Dependency management only works when the components declare what they depend on, and there is a massive body of existing useful jQuery plugins (including jQuery UI) that don't need to worry about what parts they use, it's always all there for them. That's our starting point. 

No matter what we do inside core to address dependency management, it doesn't matter for the vast majority of jQuery users unless their third-party plugins follow suit. It's as if node was built and used for a decade without npm, and you want to come in and add dependency management. Great. What is our process for doing that and helping the whole ecosystem, not just a tiny fraction? Suggestions welcome.

Not sure what a bunch of new single-purpose libraries buy you. Once you start to put them together you'll find they are bigger than jQuery if they don't have dependencies since they'll need to duplicate similar utility-ish methods internally. If they pull dependencies on each other then it seems you're back to where jQuery is today. And of course you've thrown away all jQuery plugins in the process. It seems easier to evolve jQuery than to rewrite all of it and give it new incompatible names/APIs.

As for the examples, it's really dangerous to advocate some of those code fragments because they plain just don't work on Android 2.3 which is still 20% of all Android out there and being shipped on popular phones that are still being sold. It's not just `classList` either; I don't think you can `.apply(nodeList...)` for example, I know we backed out some stuff in early 2.0 beta related to that. Given the horrible debugging environment and slow performance on Android 2.3, a lot of Chrome-using iPhone5-toting developers won't test it and are going to be oblivious to the havoc they are causing for web users.

**Comment by adamschwartz** [comment]
@dmethvin We completely take these points, especially with regards to your mention of the "proportion of the community that benefits". I think what we're trying to say here is we can have our cake and eat it too.

Can/will/should hobbyist programmers plop jQuery into a wordpress blog, add an image slider plugin, and shipit? Sure! Let's just _not additionally say_—and I know this is a bit of a strawman given there are custom builds already... but you can see how we're asking for something more powerful than that—that the most advanced JS application developers should use that same tool. It's the right tool for a large part of community, yes. But is it the right tool for the best javascript applications in the world? We think not.

That you say "The jQuery team doesn't object to splitting things out either" though indicates to me you take these points as well, and it's just a matter of deciding some of the details as to how we can do this without disrupting the core value you see jQuery providing to the developer community at large.

**Comment by zackbloom** [comment]
No one is saying jQuery is not valuable or that it should no longer be maintained.  Just that, for people building libraries (who probably know how to make dependency management work), smaller tools might be useful.

I agree that trying to turn jQuery into something it's not is a very difficult task.  I think that building small components from the ground up is probably quite a bit easier, so that's what I've been oriented towards.  The experience and collected bugfixes in jQuery are going to be very valuable in doing that, even if it doesn't mean the actual source code is being used.

**Comment by timmfin** [comment]
I think there are great points on both sides here. There is no way that youmightnotneedjquery.com will completely cover the immense number of cross-browser fixes from jquery (in the near or foreseeable future). And there is a ton of convenience for developers (of apps and libraries) to just rely on jquery and "ship it".

However, I don't think this is tenable in the long run. As browsers add features and as the DOM and other javascript APIs grow, there will be a continuing need to have libraries that cover/shim/clean/fix up those APIs. And even if jquery's monolithic-ness is not yet that big of a problem yet, I'd argue that there will be a point in time in the future when that monolithic-ness _will_ be a problem.

Maybe that problem won't come to head for a year or two. Or maybe it won't happen until the javascript community has solved/agreed upon the "dependency management" problem. But no matter when/how it happens, I think it is totally sensible to start trying to work toward that future now. Because I for one sure hope that we don't still have "everyone just rely on jquery" in five plus years (not because I don't like jquery, but because I agree with these guys that the overall ecosystem is better with small focused components).

One way to go about that is starting from the ground up, creating small components from scratch like @zackbloom says. Another way is to take jquery and slice it up into small re-usable pieces (such as making the custom-build tool even more powerful, educating more devs about AMD, etc).  Either way, I think both are useful. And I suspect that both will be necessary to get to a future where we can get all the benefits of jquery inside of a small, focused, interchangeable ecosystem of client-side javascript components.

**Pull request merged**
