### PR TITLE
Add autofocus attribute on search input

### PR DESCRIPTION
**Pull request by HarrisJT**
Just a little change which focuses the main search when the page loads, removing the need for a click. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-autofocus

### CODE REVIEW

**Comment by carusogabriel** [comment]
:-1: For me, in mobile would be a nightmare

**Comment by HarrisJT** [comment]
It just puts cursor on the element, it doesnt move your screen. Is that your issue?

**Comment by carusogabriel** [comment]
AFAIK it moves the page. If it doesn't, then is okay for me :smile:

**Comment by HarrisJT** [comment]
It appears you are correct for most browsers! A simple fix and a better one would be to .focus() the element when it appears in the viewport.

**Pull request merged**
