### PR TITLE
Add missing var statements, braces and semicolons

### PR DESCRIPTION
**Pull request by fhemberger**
A few var statements were missing in the code examples, so variables/functions might leak into the global scope.

I also added semicolons and missing braces – I know that using semicolons might be a decision of "style", but some examples used them while others were lacking them. Better to be consistent here, as people will blindly copy & paste the code snippets.

### CODE REVIEW

**Comment by mathiasbynens** [comment]
:+1:

**Comment by tonylau** [comment]
:+1:

**Comment by chrisanderton** [comment]
:thumbsup:

**Comment by Potherca** [comment]
:thumbsup:

**Comment by pseidemann** [comment]
:+1:

**Comment by mathiasbynens** [comment]
@pseidemann `request = new XMLHttpRequest;` is valid JavaScript though. No need for the `()` unless you need to pass parameters.

**Comment by tomByrer** [comment]
Nice job!  Though I'm not a ; Nazi, making the examples more copy/paste-proof is very helpful.

**Comment by zackbloom** [comment]
Thanks for doing all of this @fhemberger.  I'm on board with everything except the requirement that single line conditionals and loops use braces.  We are trying to be somewhat concise here, and I see it as more of a personal choice than a hard-and-fast rule.  If you don't mind reverting those, and merging in gh-pages, I'll merge.

**Comment by fhemberger** [comment]
Ok, no problem. Just drop the lines with the curly braces, I was more concerned about the missing var statements. It should only be a few files — Unfortunately I don't have much time this week to update the PR myself.

**Comment by tomByrer** [comment]
> except the requirement that single line conditionals and loops use braces

Well, you never know if someone will add another line inside the loop.  You do the same thing in `comparisons/elements/each/ie8.js`

``` js
forEachElement(selector, function(el, i){

});
```

But, I'm about to add a PR to his PR to help conform to your wish.

**Comment by zackbloom** [comment]
The braces in `forEach` are because it's a function, it requires braces.

I very much respect that this is partially a resource for beginners, and every syntactic bit helps, but I think the concepts are expressed just as effectively without them.

**Comment by tomByrer** [comment]
> The braces in forEach are because it's a function, it requires braces. I very much respect that this is partially a resource for beginners

Thanks for the clarification.  Yea, I have too many languages inside my head right now :)

**Comment by tomByrer** [comment]
https://github.com/fhemberger/youmightnotneedjquery/pull/1

I hope I got right of all the appropriate {}

**Comment by fhemberger** [comment]
Ok, @tomByrer's additions are now onboard. I hope everything is fine now.

**Comment by zackbloom** [comment]
Great, thanks @fhemberger

**Comment by zackbloom** [comment]
Moving this to a branch I can push to https://github.com/HubSpot/youmightnotneedjquery/pull/45

**Comment by tomByrer** [comment]
> Ok, @tomByrer's additions are now onboard

Thanks for letting me help you help Zack help recovering jQuery programmers ;)

**Pull request closed without merging**
