### PR TITLE
Fix document.querySelectorAll(). This may be wrong, you can correct me

### PR DESCRIPTION
**Pull request by ghost**
Based on the issue I made

### CODE REVIEW

**Comment by viniciuskneves** [comment]
@XtremePlayzCODE I think you misunderstood it. document.querySelectorAll will return an array of elements that you should iterate over it. And document.querySelector will return the element itself or null so you don't have to iterate over it.

**Comment by viniciuskneves** [comment]
MDN document.querySelector: Returns null if no matches are found; otherwise, it returns the first matching element.

MDN document.querySelectorAll: Returns a non-live NodeList of all the matching element nodes. ([] if no matches)

**Comment by ghost** [comment]
Ahh. I see.

**Comment by ghost** [comment]
So now this is useless almost, I will update

**Pull request closed without merging**
