### PR TITLE
replace all ajax alternatives to fetch

### PR DESCRIPTION
**Pull request by iamstarkov**
Fetch is basic standard for network requests,
see more here https://annevankesteren.nl/2016/07/fetch-101

### CODE REVIEW

**Comment by iamstarkov** [comment]
@zackbloom, @fabricionaweb, @damieng what do you think?

**Comment by fabricionaweb** [comment]
http://caniuse.com/#search=fetch

Sooner or later we have to use. For me, this PR its great! :shipit:

**Comment by iamstarkov** [comment]
@fabricionaweb for IE and Safari we can pollyfill it

**Comment by iamstarkov** [comment]
I was thinking to ask about merging this pull-request

**Comment by KaraAJC** [comment]
Would this request be merged if there are code examples to support use of fetch()?

**Comment by iamstarkov** [comment]
whatever

**Comment by FranDias** [comment]
The reason why this wasn't merged before was because the original maintainers left Hubs and now we're figuring out ownership of quite a few front end open source libraries.

Thanks for your contribution and please excuse our lack of response.

**Comment by KaraAJC** [comment]
hI @FranDias I'd still like to make examples with `.fetch()` if possible.. let me know how best to proceed, probably on another PR, correct?

**Comment by Phoenixmatrix** [comment]
Not a huge deal, but let's keep in mind that fetch doesn't support aborting requests, which is a very common requirement in the real world (the quintessential being auto-complete dropdowns), so it's not really a replacement for a lot of use cases jquery ajax (or any of the countless other alternatives, including just vanilla XMLHttpRequest) would support.

Just something to think about.

**Comment by FranDias** [comment]
True, I'll follow up with a reasonable recommendation set

**Comment by FranDias** [comment]
@karaajc feel free to make a PR 🙂

**Comment by dandv** [comment]
Is this live? I don't see any "fetch" at http://youmightnotneedjquery.com/.

**Comment by hsbtiago** [comment]
Is this live? I don't see any "fetch" at http://youmightnotneedjquery.com/. ²

**Pull request merged**
