### PR TITLE
JavaScript cleanup

### PR DESCRIPTION
**Pull request by nickserv**
I noticed some ugliness in the conversion scripts I used to generate the JavaScript for #249 that I want to clean up manually.

## Browser support

- Chrome
- Safari 7
- Firefox

If Internet Explorer support is still required (talking about the app working, not the example versions), we'd need to set up build tools for this.

### CODE REVIEW

**Comment by mscuthbert** [comment]
See #267 for two small changes needed to make IE11 not display on IE8/9 entries.  If you can get those changes into this PR (which looks great to me) then I will close #267.

**Comment by mscuthbert** [comment]
Note that the version of index.js currently on the site post Coffescript change is already non-IE supporting and requires Safari 8+ because it uses `...` syntax on `hide(...els)` and `showFirst(...els)` -- so I think that the "eliminate old browser compatibility for THIS site" issue has already been decided.

**Comment by jarikmarwede** [comment]
> Note that the version of index.js currently on the site post Coffescript change is already non-IE supporting and requires Safari 8+ because it uses `...` syntax on `hide(...els)` and `showFirst(...els)` -- so I think that the "eliminate old browser compatibility for THIS site" issue has already been decided.

I noticed the same. But that was not intended. A few days ago it still worked. It just broke after converting the CoffeScript code to plain JS. CoffeeScript also has the spread operator, but it got compiled away before.

**Review by Abbondanzo — APPROVED** [review]

**Comment by Abbondanzo** [comment]
Yeah FWIW `Object.fromEntries` isn't in IE11, as are a handful of other function calls from this PR. It's time to retire support.

As I was setting up IE11 on a new PC today, I hit so many roadblocks that it's not even possible to get a first-class installer for it. I've reconsidered this site's support and it's much easier to just drop it.

**Comment by nickserv** [comment]
> > Note that the version of index.js currently on the site post Coffescript change is already non-IE supporting and requires Safari 8+ because it uses `...` syntax on `hide(...els)` and `showFirst(...els)` -- so I think that the "eliminate old browser compatibility for THIS site" issue has already been decided.
> 
> I noticed the same. But that was not intended. A few days ago it still worked. It just broke after converting the CoffeScript code to plain JS. CoffeeScript also has the spread operator, but it got compiled away before.

Whoops sorry, I missed that. I intended for the initial JavaScript conversion to be compatible. I think dropping IE is a good idea in the long run though.

**Pull request merged**
