### PR TITLE
Add ES6 slider option

### PR DESCRIPTION
**Pull request by mscuthbert**
Add an option for ES6 slider -- can think of other things to rename to though (some keywords such as `await` didn't arrive until ES2016 or later).

Fixes the main issue in #222 but only implements one comparison example (JSON) as a demonstration.

Tested that old-ie message should display, but didn't test it on an actual Internet Explorer browser.

I didn't go ahead and drop the differences between various IE versions into a dropdown or anything like that.  I figure that this can be a later refactor once there's enough content to go there.  Will continue to discuss on #222

### CODE REVIEW

**Review by Abbondanzo — APPROVED** [review]
This is fantastic, excellent work getting this kicked off

>Add an option for ES6 slider -- can think of other things to rename to though (some keywords such as await didn't arrive until ES2016 or later).

Fair naming convention for now. We toyed with the idea of dropping browser versions and just linking out to compatibility tables on these bits of code. I think async/await was added in ES2017 (which, is ES8 IIRC) so ecmascript versions might add a bit of confusion (it's been [in Chromium for a hot minute](https://chromestatus.com/feature/5643236399906816))

>I figure that this can be a later refactor once there's enough content to go there. 

👍

**Comment by nickserv** [comment]
Technically `async/await` is ES8/2017. I think we should rename the `es6` parameter to reduce confusion. But do we want it based on the ES version, Safari version, or something else?

**Comment by jarikmarwede** [comment]
> Technically `async/await` is ES8/2017. I think we should rename the `es6` parameter to reduce confusion. But do we want it based on the ES version, Safari version, or something else?

I don't know how @Abbondanzo sees it. But my opinion is now steering towards not having any new version options except for something like "modern" which contains all the new code and has compatibility links where you can check if the feature is supported by the browsers you want to develop for.
The only other options would be for IE because we don't want to throw away the already existing examples.
The idea of a checkbox with something like "I need to support Internet Explorer" that then shows the slider for IE versions would be pretty great in my opinion.

**Comment by nickserv** [comment]
I like this idea of renaming it to "modern" and having more compatibility info. However, Safari is still not an evergreen browser, so if we end up having a bunch of things limited by Safari version, it might make sense to add a Safari slider. I don't think we need to do that now though, it can be added if needed in the future.

**Comment by jarikmarwede** [comment]
You're right. We should at least think about a Safari toggle/slider once the first examples with support by everyone but Safari show up

**Pull request merged**
